### ISSUE TITLE
Cannot install via brew

### ISSUE THREAD

**Issue by thetrompf** [EugenMayer/homebrew-dockersync#1]
Output from the failed brew install log file:

```
python
-s
/tmp/unox--homebrew-virtualenv-20170501-53323-1tihzng/target/bin/virtualenv
-p
python
/usr/local/Cellar/unox/0.2.0_1/libexec

Traceback (most recent call last):
  File "/tmp/unox--homebrew-virtualenv-20170501-53323-1tihzng/target/bin/virtualenv", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

HOMEBREW_VERSION: 1.1.13
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 46f6dc4c93b96abd528c3a0a808a5ca5a795c7f3
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9be23b70eb80e61f4b6a38c901f70e6ece2402ee
Core tap last commit: 44 seconds ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_102
macOS: 10.12.4-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: 2.7.9 => /opt/X11

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
MACOSX_DEPLOYMENT_TARGET: 10.12
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/bin:/bin:/usr/sbin:/sbin
```

If I run:

```
$ python -c "import pkg_resources"
$ echo $?
0
```

It does not break.
I tried run it through ruby which I can see the old install script did:

```
irb(main):001:0> `python -c "import pkg_resources"`
=> ""
```

And that works as well, is it something about the virtualenv that does not behave correctly?

**Comment by EugenMayer** [comment]
Idk really, since i use the best practise homebrew way. Something special/broken about your python setup?

Which OSX? Did you brew update/upgrade and run the latest brew?

**Comment by thetrompf** [comment]
The OSX version is macOS Sierra fully up-to-date.
my python is install through brew, and my brew installation is fairly up-to-date, only a month or so old. But I can try run a fully upgrade... I just have a couple of things installed that are compiled through install so it will take a while to bring it all up-to-date, but I will give it a go.

**Comment by EugenMayer** [comment]
@thetrompf i would love to help you on this, but either my level of knowledge does not allow me to do so or we can fiddle out whats different.

Which python version are you using?

**Comment by thetrompf** [comment]
Hmm.. I thought it was attached in the log file.. sorry... I use Python 2.7.13

**Comment by thetrompf** [comment]
pip version 9.0.1

**Comment by EugenMayer** [comment]
i am on

``` 
python --version
Python 2.7.10
```

though its system python

``` 
where python
/usr/bin/python
```

Yet you are the first one to complain, so not sure how to get behind the issue

**Comment by thetrompf** [comment]
I will keep digging.. I will try to reproduce the stuff brew does and let you know about what I find.

**Comment by thetrompf** [comment]
For some weird reason, the virtual environment is for me not actually installed in the temporary compilation target forlder. But if I invoke `brew install` with `-vd` (verbose and debug) I think.

I get the chance to opt-out in the shell and do fixup steps upon errors and continue.

This is what I did:

```
$ brew install eugenmayer/dockersync/unox -vd

/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/eugenmayer/homebrew-dockersync/Formula/unox.rb
==> Installing unox from eugenmayer/dockersync
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/eugenmayer/homebrew-dockersync/Formula/unox.rb
==> Downloading https://codeload.github.com/hnsl/unox/tar.gz/0.2.0
Already downloaded: /Users/<user>/Library/Caches/Homebrew/unox-0.2.0.0
==> Verifying unox-0.2.0.0 checksum
tar xzf /Users/<user>/Library/Caches/Homebrew/unox-0.2.0.0
==> Downloading https://files.pythonhosted.org/packages/5c/79/5dae7494b9f5ed061cff9a8ab8d6e1f02db352f3facf907d9eb614fb80e9/virtualenv-15.0.2.tar.gz
Already downloaded: /Users/<user>/Library/Caches/Homebrew/unox--homebrew-virtualenv-15.0.2.tar.gz
==> Verifying unox--homebrew-virtualenv-15.0.2.tar.gz checksum
tar xzf /Users/<user>/Library/Caches/Homebrew/unox--homebrew-virtualenv-15.0.2.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target --single-version-externally-managed --record=installed.txt
running install
running build
running build_py
creating build
creating build/lib
copying virtualenv.py -> build/lib
creating build/lib/virtualenv_support
copying virtualenv_support/__init__.py -> build/lib/virtualenv_support
copying virtualenv_support/argparse-1.4.0-py2.py3-none-any.whl -> build/lib/virtualenv_support
copying virtualenv_support/pip-8.1.2-py2.py3-none-any.whl -> build/lib/virtualenv_support
copying virtualenv_support/setuptools-21.2.1-py2.py3-none-any.whl -> build/lib/virtualenv_support
copying virtualenv_support/wheel-0.29.0-py2.py3-none-any.whl -> build/lib/virtualenv_support
running install_lib
copying build/lib/virtualenv.py -> /tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target/lib/python2.7/site-packages
creating /tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target/lib/python2.7/site-packages/virtualenv_support
copying build/lib/virtualenv_support/__init__.py -> /tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target/lib/python2.7/site-packages/virtualenv_support
copying build/lib/virtualenv_support/argparse-1.4.0-py2.py3-none-any.whl -> /tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target/lib/python2.7/site-packages/virtualenv_support
copying build/lib/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl -> /tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target/lib/python2.7/site-packages/virtualenv_support
copying build/lib/virtualenv_support/setuptools-21.2.1-py2.py3-none-any.whl -> /tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target/lib/python2.7/site-packages/virtualenv_support
copying build/lib/virtualenv_support/wheel-0.29.0-py2.py3-none-any.whl -> /tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target/lib/python2.7/site-packages/virtualenv_support
byte-compiling /tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target/lib/python2.7/site-packages/virtualenv.py to virtualenv.pyc
byte-compiling /tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target/lib/python2.7/site-packages/virtualenv_support/__init__.py to __init__.pyc
running install_egg_info
running egg_info
writing virtualenv.egg-info/PKG-INFO
writing top-level names to virtualenv.egg-info/top_level.txt
writing dependency_links to virtualenv.egg-info/dependency_links.txt
writing entry points to virtualenv.egg-info/entry_points.txt
reading manifest file 'virtualenv.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*' found under directory 'docs/_templates'
warning: no previously-included files matching '*' found under directory 'docs/_build'
writing manifest file 'virtualenv.egg-info/SOURCES.txt'
Copying virtualenv.egg-info to /tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target/lib/python2.7/site-packages/virtualenv-15.0.2-py2.7.egg-info
running install_scripts
Installing virtualenv script to /tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target/bin
writing list of installed files to 'installed.txt'
==> python -s /tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target/bin/virtualenv -p python /usr/local/Cellar/unox/0.2.0_1/libexec
Traceback (most recent call last):
  File "/tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target/bin/virtualenv", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: python -s /tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target/bin/virtualenv -p python /usr/local/Cellar/unox/0.2.0_1/libexec
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 5
When you exit this shell, you will return to the menu.

$ cd /tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target
$ bin/virtualenv .

New python executable in /private/tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target/bin/python
Installing setuptools, pip, wheel...done.
Birna% bin/pip install setuptools
Requirement already satisfied: setuptools in ./lib/python2.7/site-packages
Requirement already satisfied: packaging>=16.8 in ./lib/python2.7/site-packages (from setuptools)
Requirement already satisfied: appdirs>=1.4.0 in ./lib/python2.7/site-packages (from setuptools)
Requirement already satisfied: six>=1.6.0 in ./lib/python2.7/site-packages (from setuptools)
Requirement already satisfied: pyparsing in ./lib/python2.7/site-packages (from packaging>=16.8->setuptools)

$ python -s /tmp/unox--homebrew-virtualenv-20170501-2724-1jvay85/target/bin/virtualenv -p python /usr/local/Cellar/unox/0.2.0_1/libexec

Already using interpreter /usr/bin/python
New python executable in /usr/local/Cellar/unox/0.2.0_1/libexec/bin/python
Installing setuptools, pip, wheel...done.

$ exit

1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 2

```

And now the installation continues and everything works.

**Comment by thetrompf** [comment]
I don't know if the unox--homebrew-virtualenv brew package is supposed to come with the virtualenv pre-installed or not when the setup procedure unpacks it, but in my setup for some reason it doesn't hit the virtualenv (with setuptools and wheel and what not) when that package is just unpacked, and I have to install it manually in the temporary compilation directory and continue the install manually.

I wonder if you hit a systemwide installed setuptools package when you install unox, or in your case actually have the virtualenv applied to the temporary compile target directory.

**Comment by ramyrabi3** [comment]
Any update on this? I'm facing the same issue here..

**Comment by EugenMayer** [comment]
@ramyrabi3 not working and this (and wont working on this), some odd python env hickups i do not really want to cope with.

If that does not work, install unox "they way you like", manually or pip_install or whatever https://github.com/hnsl/unox#manual-installation

This is just not really a docker-sync issue, nor a unox issue, its more a brew + multi python env or broken permissions. try brew doctor and fix all, see if that helps

**Comment by ramyrabi3** [comment]
Thanks @EugenMayer 
Installation manually worked fine, however `docker-sync start`, returns `zsh: command not found: docker-sync` . Should I add something to PATH or so ?

**Comment by EugenMayer** [comment]
maybe fixed in #6?

**Comment by ahazebroucq** [comment]
I also had this issue, on a brand new macOS install. It seems that it's not fixed with #6.

I was able to manually install unox (using `pip3` instead of `pip`) but it seems that unfortunately I *need* `brew install eugenmayer/dockersync/unox` to work before installing docker-sync, as `gem install docker-sync` will fail if unox is manually installed : 
````bash
Error: No such keg: /usr/local/Cellar/unox
     warning  You installed unison-fsmonitor (unox) the old legacy way (i.e. not using brew). We need to fix that.
Uninstall legacy unison-fsmonitor (unox)? (y/N)
       error  Failed to remove legacy unison-fsmonitor (unox). Please delete /usr/local/bin/unison-fsmonitor manually and try again.
````

Any idea how I could help debugging this ?

---

Edit : found a solution ! Just install unox with python3 : 
````
brew install unox --with-python3
````

**Comment by EugenMayer** [comment]
should have been fixed by using python2 https://github.com/EugenMayer/homebrew-dockersync/commit/1b80a65cba2c03b602e0dca9fcdbb5404db0bf95
